version: '2'
name: technical-indicator-live-pipeline
networks:
  redpanda-network:
    external: true
    name: redpanda-quickstart-one-broker_redpanda_network

services:
  trade:
    build:
      context: ../trade
      dockerfile: Dockerfile
    networks:
      - redpanda-network
    #env_file:
      #- ../trade/setting.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda-0:9092 
      - KAFKA_TOPIC=trade_live
      - KRAKEN_PAIRS=["BTC/USD","BTC/EUR", "ETH/EUR","ETH/USD"]
      - DATA_SOURCE=live 
    restart: always
    
  candle:
    build:
      context: ../candle
      dockerfile: Dockerfile
    networks:
      - redpanda-network
    #env_file:
      #- ../candle/setting.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda-0:9092
      - KAFKA_INPUT_TOPIC=trade_live
      - KAFKA_OUTPUT_TOPIC=candle_live
      - KAFKA_CONSUMER_GROUP=candle_live_group
      - CANDLE_SECONDS=60
      - EMIT_INCOMPLETE_CANDLE=False
      - DATA_SOURCE=live
    restart: always

  technical-indicator:
    build:
      context: ../technical-indicator
      dockerfile: Dockerfile
    networks:
      - redpanda-network
    #env_file:
      #- ../technical-indicator/setting.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda-0:9092
      - KAFKA_INPUT_TOPIC=candle_live
      - KAFKA_OUTPUT_TOPIC=technical-indicator_live
      - KAFKA_CONSUMER_GROUP=technical_indicator_live_group
      - MAX_CANDLE_IN_STATE=120
      - CANDLE_SECONDS=60
      - DATA_SOURCE=live
    restart: always 
  
  feature-store:
    build:
      context: ../feature-store
      dockerfile: Dockerfile
    networks:
      - redpanda-network
    env_file:
      #- ../feature-store/setting.env
      - ../feature-store/credentials.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda-0:9092
      - KAFKA_INPUT_TOPIC=technical-indicator_live
      - KAFKA_CONSUMER_GROUP=feature_store_consumer_live_group
      - FEATURE_GROUP_NAME=technical_indicator
      - FEATURE_GROUP_VERSION=1
      - FEATURE_GROUP_PRIMARY_KEY=["pair","candle_seconds"]
      - FEATURE_GROUP_EVENT_TIME=timestamp_ms
      - FEATURE_GROUP_MATEIALIZATION_INTERVAL=15
      - DATA_SOURCE=live
    restart: always

