version: '2'
name: technical-indicator-pipeline
networks:
  redpanda-network:
    external: true
    name: redpanda-quickstart-one-broker_redpanda_network

services:
  trade:
    build:
      context: ../trade
      dockerfile: Dockerfile
    networks:
      - redpanda-network
    env_file:
      - ../trade/setting.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda-0:9092  
    restart: always
    
  candle:
    build:
      context: ../candle
      dockerfile: Dockerfile
    networks:
      - redpanda-network
    env_file:
      - ../candle/setting.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda-0:9092
    restart: always

  technical-indicator:
    build:
      context: ../technical-indicator
      dockerfile: Dockerfile
    networks:
      - redpanda-network
    env_file:
      - ../technical-indicator/setting.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda-0:9092
    restart: always 
  
  feature-store:
    build:
      context: ../feature-store
      dockerfile: Dockerfile
    networks:
      - redpanda-network
    env_file:
      - ../feature-store/setting.env
      - ../feature-store/credentials.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda-0:9092
    restart: always

