[project]
name = "feature-store"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "hopsworks>=4.1.8",
    "loguru>=0.7.3",
    "pyarrow>=19.0.1",
    "pydantic-settings>=2.6.1",
    "quixstreams>=3.10.0",
]
